### ISSUE TITLE
Address changed and balance incorrectly shows zero

### ISSUE THREAD

**Issue by sacriverdon** [ShiftNrg/shift-nano#1]
### Expected behaviour
Display correct address and correct balance
### Actual behaviour
Displays a different unknown address and zero balance
### Steps to reproduce
Download desktop wallet and install
Create new account and write down secret passphrase
Log out and in again to ensure the secret passphrase works
Deposit 1 SHIFT into wallet and wait a few minutes to confirm the correct balance in wallet
Log out and in again
Deposit 14 more SHIFT into wallet and wait a few minutes to confirm the correct balance in wallet
Also verify balance on https://explorer.shiftnrg.org/
Log out and log in again a few hours later
Balance shows zero and a different address is displayed

**Comment by sacriverdon** [comment]
I figured out the problem. I typed the passphrase in all CAPS and now I can see my wallet balance and correct address again.

**Comment by Bernieman00** [comment]
Hi. I open Nano Wallet and the balance shows zero. The adress is correct. I checked on the blockchain and show my balance correct. How i do for the nano wallet shows the correct balance?
